// Common clinical abbreviations, shown as a tooltip and in a per-case list (display only: the case text is unchanged).
// Written from standard usage, not from the cases; an abbreviation with two common meanings shows both. The object is
// plain JSON so tools/count_abbreviations.py can read it.
export const ABBREVIATIONS = {
  "A&O": "alert and oriented",
  "A&Ox3": "alert and oriented to person, place and time",
  "AAA": "abdominal aortic aneurysm",
  "Abd": "abdominal",
  "abd": "abdominal",
  "ABG": "arterial blood gas",
  "Abx": "antibiotics",
  "ABX": "antibiotics",
  "ACEi": "ACE inhibitor",
  "ACS": "acute coronary syndrome",
  "ADL": "activities of daily living",
  "AF": "atrial fibrillation, or afebrile",
  "Afib": "atrial fibrillation",
  "AKI": "acute kidney injury",
  "ALT": "alanine aminotransferase",
  "AMS": "altered mental status",
  "AOx3": "alert and oriented to person, place and time",
  "appy": "appendectomy",
  "ARB": "angiotensin receptor blocker",
  "ASA": "aspirin",
  "AST": "aspartate aminotransferase",
  "AxOx3": "alert and oriented to person, place and time",
  "b/l": "bilateral",
  "BCx": "blood culture",
  "bHCG": "beta human chorionic gonadotropin (pregnancy test)",
  "BID": "twice a day",
  "bid": "twice a day",
  "BLE": "both lower extremities",
  "BM": "bowel movement",
  "BMP": "basic metabolic panel",
  "BNP": "B-type natriuretic peptide",
  "BP": "blood pressure",
  "BPH": "benign prostatic hyperplasia",
  "BRBPR": "bright red blood per rectum",
  "BS": "bowel sounds",
  "BUE": "both upper extremities",
  "BUN": "blood urea nitrogen",
  "c/o": "complains of",
  "CABG": "coronary artery bypass graft",
  "CAD": "coronary artery disease",
  "CBC": "complete blood count",
  "CCY": "cholecystectomy",
  "CHEM7": "basic metabolic panel",
  "CHF": "congestive heart failure",
  "chole": "cholecystectomy",
  "CKD": "chronic kidney disease",
  "CMP": "comprehensive metabolic panel",
  "CN": "cranial nerves",
  "COPD": "chronic obstructive pulmonary disease",
  "CP": "chest pain",
  "Cr": "creatinine",
  "CRP": "C-reactive protein",
  "CT": "computed tomography",
  "CTA": "CT angiography, or clear to auscultation",
  "CTAB": "clear to auscultation bilaterally",
  "CTPA": "CT pulmonary angiography",
  "CV": "cardiovascular",
  "CVA": "stroke (cerebrovascular accident), or costovertebral angle",
  "CVAT": "costovertebral angle tenderness",
  "CXR": "chest X-ray",
  "D5W": "5% dextrose in water",
  "DBP": "diastolic blood pressure",
  "DM": "diabetes mellitus",
  "DM2": "type 2 diabetes mellitus",
  "DOE": "dyspnoea on exertion",
  "DTR": "deep tendon reflexes",
  "DVT": "deep vein thrombosis",
  "Dx": "diagnosis",
  "dx": "diagnosis",
  "ECG": "electrocardiogram",
  "ED": "emergency department",
  "EF": "ejection fraction",
  "EGD": "upper endoscopy (oesophagogastroduodenoscopy)",
  "EKG": "electrocardiogram",
  "EOMI": "extraocular movements intact",
  "ERCP": "endoscopic retrograde cholangiopancreatography",
  "ESR": "erythrocyte sedimentation rate",
  "ESRD": "end-stage renal disease",
  "ETOH": "alcohol",
  "EtOH": "alcohol",
  "ETT": "exercise treadmill test, or endotracheal tube",
  "F/C": "fevers and chills",
  "f/u": "follow-up",
  "FAST": "focused assessment with sonography in trauma",
  "FROM": "full range of motion",
  "GCS": "Glasgow Coma Scale",
  "GERD": "gastro-oesophageal reflux disease",
  "GI": "gastrointestinal",
  "Glu": "glucose",
  "GU": "genitourinary",
  "h/o": "history of",
  "HA": "headache",
  "HBV": "hepatitis B virus",
  "hCG": "human chorionic gonadotropin (pregnancy test)",
  "HCG": "human chorionic gonadotropin (pregnancy test)",
  "HCO3": "bicarbonate",
  "Hct": "haematocrit",
  "HCTZ": "hydrochlorothiazide",
  "HCV": "hepatitis C virus",
  "HD": "haemodialysis",
  "HEENT": "head, eyes, ears, nose and throat",
  "HFpEF": "heart failure with preserved ejection fraction",
  "HFrEF": "heart failure with reduced ejection fraction",
  "Hgb": "haemoglobin",
  "HIDA": "hepatobiliary iminodiacetic acid scan",
  "HIV": "human immunodeficiency virus",
  "HLD": "hyperlipidaemia",
  "HPI": "history of present illness",
  "HR": "heart rate",
  "hr": "hour",
  "hrs": "hours",
  "HSV": "herpes simplex virus",
  "HTN": "hypertension",
  "Hx": "history",
  "hx": "history",
  "IBD": "inflammatory bowel disease",
  "IBS": "irritable bowel syndrome",
  "ICU": "intensive care unit",
  "IM": "intramuscular",
  "INR": "international normalised ratio",
  "IUD": "intrauterine device",
  "IV": "intravenous",
  "iv": "intravenous",
  "IVF": "intravenous fluids",
  "JVD": "jugular venous distension",
  "KCl": "potassium chloride",
  "KUB": "kidney, ureter and bladder X-ray",
  "LAD": "lymphadenopathy, or left anterior descending artery",
  "lap": "laparoscopic",
  "LBP": "low back pain",
  "LE": "lower extremity",
  "LEs": "lower extremities",
  "LFT": "liver function tests",
  "LFTs": "liver function tests",
  "LLL": "left lower lobe",
  "LLQ": "left lower quadrant",
  "LMP": "last menstrual period",
  "LOC": "loss of consciousness",
  "LR": "lactated Ringer's solution",
  "LUL": "left upper lobe",
  "LUQ": "left upper quadrant",
  "mcg": "microgram",
  "mEq": "milliequivalent",
  "mg": "milligram",
  "MI": "myocardial infarction",
  "mL": "millilitre",
  "MMM": "moist mucous membranes",
  "MRCP": "magnetic resonance cholangiopancreatography",
  "MRI": "magnetic resonance imaging",
  "MRSA": "methicillin-resistant Staphylococcus aureus",
  "MSK": "musculoskeletal",
  "N/V": "nausea and vomiting",
  "N/V/D": "nausea, vomiting and diarrhoea",
  "NABS": "normal active bowel sounds",
  "NAD": "no acute distress",
  "NC": "nasal cannula",
  "ND": "non-distended",
  "NGT": "nasogastric tube",
  "NKDA": "no known drug allergies",
  "nl": "normal",
  "NPO": "nothing by mouth",
  "NS": "normal saline",
  "NSAID": "non-steroidal anti-inflammatory drug",
  "NSAIDs": "non-steroidal anti-inflammatory drugs",
  "NT": "non-tender",
  "NT/ND": "non-tender, non-distended",
  "NTND": "non-tender, non-distended",
  "O2": "oxygen",
  "OCP": "oral contraceptive pill",
  "OSA": "obstructive sleep apnoea",
  "OTC": "over the counter",
  "PAD": "peripheral artery disease",
  "PCN": "penicillin",
  "PCP": "primary care physician",
  "PE": "pulmonary embolism, or physical examination",
  "PERRL": "pupils equal, round, reactive to light",
  "PERRLA": "pupils equal, round, reactive to light and accommodation",
  "PID": "pelvic inflammatory disease",
  "Plt": "platelets",
  "PMD": "primary medical doctor",
  "PMH": "past medical history",
  "PNA": "pneumonia",
  "PO": "by mouth",
  "po": "by mouth",
  "POCUS": "point-of-care ultrasound",
  "PPI": "proton pump inhibitor",
  "PRN": "as needed",
  "prn": "as needed",
  "PSH": "past surgical history",
  "pt": "patient",
  "PT": "prothrombin time",
  "pts": "patients",
  "PTT": "partial thromboplastin time",
  "PUD": "peptic ulcer disease",
  "PVD": "peripheral vascular disease",
  "q12h": "every 12 hours",
  "q4h": "every 4 hours",
  "q6h": "every 6 hours",
  "Q6H": "every 6 hours",
  "q8h": "every 8 hours",
  "Q8H": "every 8 hours",
  "QD": "once a day",
  "qd": "once a day",
  "QHS": "at bedtime",
  "QID": "four times a day",
  "r/o": "rule out",
  "RA": "room air",
  "RLL": "right lower lobe",
  "RLQ": "right lower quadrant",
  "RML": "right middle lobe",
  "ROM": "range of motion",
  "ROS": "review of systems",
  "RR": "respiratory rate",
  "RRR": "regular rate and rhythm",
  "RUL": "right upper lobe",
  "RUQ": "right upper quadrant",
  "s/p": "status post (after)",
  "SBO": "small bowel obstruction",
  "SBP": "systolic blood pressure",
  "SC": "subcutaneous",
  "SIRS": "systemic inflammatory response syndrome",
  "SL": "sublingual",
  "SOB": "shortness of breath",
  "SpO2": "oxygen saturation",
  "SQ": "subcutaneous",
  "SSRI": "selective serotonin reuptake inhibitor",
  "STD": "sexually transmitted disease",
  "STI": "sexually transmitted infection",
  "SVT": "supraventricular tachycardia",
  "Sx": "symptoms",
  "sx": "symptoms",
  "T": "temperature",
  "Tbili": "total bilirubin",
  "Temp": "temperature",
  "TIA": "transient ischaemic attack",
  "TID": "three times a day",
  "tid": "three times a day",
  "TOA": "tubo-ovarian abscess",
  "Trop": "troponin",
  "TTE": "transthoracic echocardiogram",
  "TTP": "tender to palpation",
  "Tx": "treatment",
  "tx": "treatment",
  "U/A": "urinalysis",
  "UA": "urinalysis",
  "UCG": "urine pregnancy test",
  "UCx": "urine culture",
  "UE": "upper extremity",
  "UOP": "urine output",
  "UPT": "urine pregnancy test",
  "URI": "upper respiratory infection",
  "US": "ultrasound",
  "UTI": "urinary tract infection",
  "V/Q": "ventilation-perfusion scan",
  "VBG": "venous blood gas",
  "VSS": "vital signs stable",
  "VT": "ventricular tachycardia",
  "w/": "with",
  "w/o": "without",
  "WBC": "white blood cell count",
  "WNL": "within normal limits",
  "wnl": "within normal limits",
  "y/o": "years old",
  "yo": "years old"
};

// Display helper: the text is split around known abbreviations; each one becomes <abbr> with its meaning as the
// tooltip (and on focus, for touch screens). Matching is case-sensitive on whole tokens, as tools/count_abbreviations.py.
import { h } from './dom.js';

const KEYS = Object.keys(ABBREVIATIONS).sort((a, b) => b.length - a.length);
const esc = (s) => s.replace(/[.*+?^${}()|[\]\\/&]/g, '\\$&');
const RE = new RegExp(`(?<![A-Za-z0-9/])(${KEYS.map(esc).join('|')})(?![A-Za-z0-9/])`, 'g');

export function withAbbr(text) {
  if (!text) return text;
  const out = []; let last = 0;
  for (const m of String(text).matchAll(RE)) {
    if (m.index > last) out.push(text.slice(last, m.index));
    out.push(h('abbr', { class: 'abbr', title: ABBREVIATIONS[m[1]], 'data-full': ABBREVIATIONS[m[1]], tabindex: '0' }, m[1]));
    last = m.index + m[1].length;
  }
  if (last < text.length) out.push(text.slice(last));
  return out;
}

export function abbreviationsIn(texts) {
  const seen = new Set();
  for (const t of texts) for (const m of String(t || '').matchAll(RE)) seen.add(m[1]);
  return [...seen].sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' })).map((k) => [k, ABBREVIATIONS[k]]);
}
